### ISSUE TITLE
tests broken: missing verbose field in Config

### ISSUE THREAD

**Issue by 0xSaiNova** [0xSaiNova/heft#45]
all integration tests are failing to compile after adding the verbose field to Config in PR #38. 

## error

```
error[E0063]: missing field `verbose` in initializer of `Config`
   --> tests/integration_test.rs:29:18
    |
29  |     let config = Config {
    |                  ^^^^^^ missing `verbose`
```

happens in 11 places throughout tests/integration_test.rs

## what happened

PR #38 added `verbose: bool` to the Config struct but didn't update the test fixtures. every place in the tests that creates a Config manually is now missing the field.

## fix needed

add `verbose: false` to all Config initializers in tests/integration_test.rs. something like:

```rust
let config = Config {
    roots: vec![temp.clone()],
    timeout: Duration::from_secs(30),
    skip_docker: true,
    json_output: false,
    verbose: false,  // <-- add this
    platform: Platform::Linux,
};
```

## impact

- can't run tests locally with `cargo test`
- CI is probably broken
- blocks any PR that needs test validation

this is blocking development so should be fixed asap
